name: Trigger auto deployment

on:
  # 手動実行用トリガー
  workflow_dispatch:      

env:
  CONTAINER_REGISTRY: acrhihorikarevisions.azurecr.io
  RESOURCE_GROUP_NAME: rg-aca-revision-deploy
  CONTAINERAPP_NAME: ctapp-aca-revision-deploy2

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set repository name to env
        run: | 
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          context: ./

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Add revision to ACA
        uses: horihiro/aca-preview@v0.0.1-alpha2
        with:
          resource-group: ${{ env.RESOURCE_GROUP_NAME }}
          name: ${{ env.CONTAINERAPP_NAME }}
          revision-name-suffix: ${{ env.SHORT_SHA }}
          image: ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}

